const express = require("express")
const bodyParser = require("body-parser")
const path = require("path")
require("dotenv").config()
const router = require("./router")
const cors = require("cors")
const app = express()
app.use(bodyParser.json())
app.use(cors())
app.use("/", router)

app.use(express.static(path.join(__dirname, "public")))
app.use(bodyParser.urlencoded({ extended: false }))

app.listen(process.env.APP_PORT, () => console.log("Express server is running at port", process.env.APP_PORT))
